panel:
    name: rev
    max_connections: 1024
    options:
        addr: 0.0.0.0
        port: 8000
operator:
    name: round_robin
    options:
address_book:
    name: csv
    options:
        file: "examples/servers.csv"